ASYNC_DB_DRIVER = "mysql+asyncmy"
DB_DRIVER = "mysql"
DB_USERNAME = "root"
DB_PASSWORD = "root"
DB_HOST = "localhost"
DB_PORT = "3306" #SHOW GLOBAL VARIABLES LIKE 'PORT';
DB_NAME = "pseudo_sys"

ASYNC_SQLALCHEMY_DATABASE_URI = f'{ASYNC_DB_DRIVER}://{DB_USERNAME}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}'
SQLALCHEMY_DATABASE_URI = f'{DB_DRIVER}://{DB_USERNAME}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}'
